Created Safegraph_py pytest functionality
SafeGraphInc/safegraph_py pull request #31
Opened 2020-09-24 08:13 UTC by Trippl7777

Please review the files to make sure nothing looks strange.

I intentionally left out Brian's function because I would like to see how hard it is for someone to make a test file for a function they have created - I believe it will help me write a tutorial. Besides that, we should have 100% coverage of all functions.

2020-09-25 22:22 UTC, ryanfoxsquire requested changes
@Trippl7777  In addition to inlin comments 3 other themes: 

1. can we remove a lot of testing and debugging code that is currently commented out? I would prefer to have no commented-out code being pushed to production. We can have comments that explain the production code. We can have external documentation in the readme to talk about debugging/testing best practices if you think those are useful. But let's not leave testing code in production commented out. 

2. How big are all the testing files? I couldn't quite tell in this PR. hopefully they are small, i don't think we need more than 100 row example CSVs to test the read functions (maybe less?) and we want to make the data as small as possible so that the repo does not get too large. 

3. 

Instead of importing all of the necessary libraries for each test function file, we should just import the entire repo.

So instead of
```
from safegraph_py_functions.safegraph_py_functions import load_json_nan, explode_json_array, explode_json_array_fast
import pytest
import pandas as pd
import pandas.util.testing as pdt
import json @
```

Just do:
```
from safegraph_py_functions.safegraph_py_functions import *
import pytest
import pandas.util.testing as pdt
```

This should import pandas and json, and any other necessary libraries

Why? If we accidentally delete the import json from the production file, then the tests would still pass. We want to test everything in the production file as stand alone, and not have to duplicate imports. So in the test file only import libraries that are not required in production but required for testing.

2020-09-25 22:22 UTC, ryanfoxsquire commented on safegraph_py_functions/safegraph_py_functions.py
> +    # print(f"You are about to load in {len(core_files)} core files")
@Trippl7777  let's not have commented print functions like this pushed to master. If you think it is sometimes useful to return this, then we can put it under a default False parameter flag like `verbose` or `debug_mode`

2020-09-25 22:22 UTC, ryanfoxsquire commented on safegraph_py_functions/safegraph_py_functions.py
> +    # print(f"You are about to load in {len(pattern_files)} pattern files")
@Trippl7777  same as line 257

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/explode_array_test.py
> +data = {'safegraph_place_id':  ['sg:64d0ee4695af4ab4906fe82997ead9ff', 'sg:001955fa1c994b4c8c877316a66dd986', 'sg:001e39c6b18645a5950b13a278b242c3', 'sg:00267c6356804259b6c92ba31c842f5a', 'sg:0029991
@Trippl7777  can we call this something more informative like `test_input_data` instead of just `data` ?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/explode_array_test.py
> +def add(a, b):
@Trippl7777  is this add and 5 == 5 code / always_pass_test still necessary or can we remove for clarity?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/json_explode_merge_test.py
> +var2 = 'test'
@Trippl7777  delete this?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/json_explode_merge_test.py
> +data = {'safegraph_place_id':  ['sg:64d0ee4695af4ab4906fe82997ead9ff', 'sg:001955fa1c994b4c8c877316a66dd986', 'sg:001e39c6b18645a5950b13a278b242c3', 'sg:00267c6356804259b6c92ba31c842f5a', 'sg:0029991
rename `test_input_data` for clarity

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/explode_array_test.py
> +cols = ['safegraph_place_id', 'visits_by_day', 'visitor_home_cbgs', 'date_range_start', 'visitor_home_cbgs_key', 'visitor_home_cbgs_value']
@Trippl7777  is this ever used for anything? can we remove `cols` ?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/explode_array_test.py
> +
@Trippl7777  can we remove unnecessary returns / blank lines for consistent formatting?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/json_explode_merge_test.py
> +### |-------------- Only uncomment when you need to test pytest functionality -------------|
@Trippl7777  do we need this in every test file? Do we need it at all? Ideally we do not commit commented testing /debugging code into the repo unless it is really necessary. You can add this to the readme if you think it is important to keep around to help future people with debugging

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/read_pattern_test.py
> +file_path = "tests/mock_data_v2020_09/weekly_demo.csv.gz"
@Trippl7777  more informative var name? like `input_test_data_file_path` ?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/read_pattern_test.py
> +file_path_multi = "tests/mock_data_v2020_09/weekly_multi"
@Trippl7777 more informative var name as above?

2020-09-25 22:22 UTC, ryanfoxsquire commented on tests/read_pattern_test.py
> +week1 = pd.read_csv(week1_path, dtype={'postal_code': str, 'phone_number': str, 'naics_code': str, 'latitude': float, 'longitude': float, 'poi_cbg': str, 'census_block_group': str,'primary_number': s
@Trippl7777 can save a little clutter by saving (on line 21)  a dict `sg_dtypes` where you define the dtypes then use this in both line 22 and line 23

2020-09-26 00:11 UTC, Trippl7777 commented on safegraph_py_functions/safegraph_py_functions.py
> +    # print(f"You are about to load in {len(core_files)} core files")
There is a strange bug with pytest and this print function, but it is definitely not needed. I will remove it

2020-09-26 00:26 UTC, Trippl7777 commented on tests/explode_array_test.py
> +data = {'safegraph_place_id':  ['sg:64d0ee4695af4ab4906fe82997ead9ff', 'sg:001955fa1c994b4c8c877316a66dd986', 'sg:001e39c6b18645a5950b13a278b242c3', 'sg:00267c6356804259b6c92ba31c842f5a', 'sg:0029991
on it

2020-09-26 00:27 UTC, Trippl7777 commented on tests/explode_array_test.py
> +cols = ['safegraph_place_id', 'visits_by_day', 'visitor_home_cbgs', 'date_range_start', 'visitor_home_cbgs_key', 'visitor_home_cbgs_value']
should be fine to remove

2020-09-26 00:28 UTC, Trippl7777 commented on tests/explode_array_test.py
> +def add(a, b):
yeah, I will get rid of the pass_tests

2020-09-28 19:05 UTC, Trippl7777 reviewed
The total size of all of the test data combined is: 275 KB 

would you like that trimmed down or is that ok?

2020-09-28 19:05 UTC, Trippl7777 commented on tests/explode_array_test.py
> +
Done

2020-09-28 19:06 UTC, Trippl7777 commented
The total size of all of the test data combined is: 275 KB

would you like that trimmed down or is that ok?

The entire test runs in 20-35sec

2020-09-28 21:21 UTC, ryanfoxsquire requested changes
only found 1 small inconsistency. Also @Trippl7777  was there somethgin else you mentiond on the call you wanted to fix? Let me know in thread when this is ready to merge. let me know in thread when ready to merge thanks!

2020-09-28 21:21 UTC, ryanfoxsquire commented on tests/json_explode_test.py
> +df = pd.DataFrame (test_input_data, columns = ['safegraph_place_id', 'visits_by_day', 'visitor_home_cbgs', 'date_range_start'])
@Trippl7777  do we need the "columns" input here? You don't have it `json_explode_merge_test.py`. If it is not essential, then would be good to remove it.

2020-09-28 21:29 UTC, ryanfoxsquire approved these changes
great work!

2020-09-28 21:31 UTC, Trippl7777 commented
Great. Should be ready to merge now!

2020-09-28 21:32 UTC, merged